spring.application.name=serverIfBank

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/ifbank?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root37}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bancodigital133@gmail.com
spring.mail.password=chmkmsdrccfhzjtd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:4200


jwt.secret=minha-chave-secreta-super-longa-ifbank-2026-segura
jwt.expiration=86400000